apiVersion: v1
kind: Service
metadata:
  name: bookstore-book
  namespace: bookstore
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30052
  selector:
    app: bookstore-book
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-book
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore-book
  template:
    metadata:
      labels:
        app: bookstore-book
    spec:
      containers:
      - image: mypractice96/bs-book:latest
        name: bookstore-book
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "2" 
        ports:
        - containerPort: 8081
          name: book
 
 
        